-- THIS IS FOR THE SESSION
SET TIME ZONE 'UTC';

SHOW TIMEZONE ;
-- ALL OUR FUTURE SESSIONS WILL BE IN UTC
ALTER USER postgres SET timezone = 'UTC';

SHOW TIMEZONE;

-- POSTGRES WILL SAVE EVERYTHING IN UTC