SELECT now();

-- CREATE THE TABLE
CREATE TABLE timezones
(
    ts TIMESTAMP WITHOUT TIME ZONE,
    tz TIMESTAMP WITH TIME ZONE
);
-- ADD DATA
INSERT INTO timezones
VALUES (TIMESTAMP WITHOUT TIME ZONE '2000-01-01 10:00:00-5',
        TIMESTAMP WITH TIME ZONE '2000-01-01 10:00:00-5');
-- GET THE DATA
SELECT *
FROM timezones;
